org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true
# 项目路径含中文，AGP 7.4 默认会拒绝，必须保留
android.overridePathCheck=true
kotlin.code.style=official
